# Generated by Django 3.0.2 on 2020-01-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colores',
            name='id_color',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='id_marca',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tallas',
            name='id_talla',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
